name: QulertsIosSDK

on:
  push:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Create Tag
      run: |
        git tag -a 1.0.${{ github.run_number }} -m "Release version 1.0.${{ github.run_number }}"
        git push origin 1.0.${{ github.run_number }}
